//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class persons
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_employ { get; set; }
        public Nullable<System.DateTime> date_uneploy { get; set; }
        public int status { get; set; }
        public int id_dep { get; set; }
        public int id_post { get; set; }
    }
}
